-- Fact: one row per player per gameweek (prefix pg_) -- the grain every
-- player-level dashboard query aggregates over.
select
    player_id         as pg_id,
    points            as pg_points,
    goals_scored      as pg_goals,
    assists           as pg_assists,
    minutes           as pg_minutes,
    clean_sheets      as pg_clean_sheets,
    goals_conceded    as pg_goals_conceded,
    own_goals         as pg_own_goals,
    penalties_saved   as pg_pens_saved,
    penalties_missed  as pg_pens_missed,
    yellow_cards      as pg_yellow_cards,
    red_cards         as pg_red_cards,
    saves             as pg_saves,
    bonus_points      as pg_bonus,
    bps               as pg_bps,
    influence         as pg_influence,
    creativity        as pg_creativity,
    threat            as pg_threat,
    ict_index         as pg_ict,
    defcons           as pg_defcons,
    starts            as pg_starts,
    xG                as pg_xG,
    xA                as pg_xA,
    XGI               as pg_XGI,
    xGa               as pg_xGa,
    dream_team        as pg_dreamteam,
    played            as pg_played,
    gameweek_id       as pg_gameweek
from {{ ref('stg_player_gameweek') }}
