name: fpl_pipeline
version: '1.0.0'
profile: fpl_pipeline

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  fpl_pipeline:
    staging:
      +schema: stg
      +materialized: view

    analytics:
      +schema: analytics
      +materialized: table